version: 2.1

orbs:
  artsy-remote-docker: artsy/remote-docker@0.1.1
  codecov: codecov/codecov@1.0.5
  hokusai: artsy/hokusai@0.7.2
  horizon: artsy/release@0.0.1
  node: artsy/node@0.1.0
  yarn: artsy/yarn@2.1.1

jobs:
  acceptance:
    docker:
      - image: circleci/node:10-stretch-browsers
    steps:
      - yarn/setup
      - run:
          name: Acceptance Tests
          command: yarn acceptance src/test/acceptance/*.js

  acceptance_cypress:
    docker:
      - image: circleci/node:10-stretch-browsers
    steps:
      - yarn/setup
      - run:
          name: Cypress Tests
          command: yarn test:smoke

  validate_production_schema:
    executor: node/build
    steps:
      - yarn/setup
      - run:
          name: Validate Production Schema
          command: node scripts/validateSchemas.js production

  danger:
    executor: node/build
    steps:
      - yarn/setup
      - run:
          name: Danger
          command: DANGER_GITHUB_API_TOKEN="15e52de81a772b174cc5""e1813d0083564c69c325" yarn danger ci

not_master_or_staging_or_release: &not_master_or_staging_or_release
  filters:
    branches:
      ignore:
        - master
        - staging
        - release

not_staging_or_release: &not_staging_or_release
  filters:
    branches:
      ignore:
        - staging
        - release

only_master: &only_master
  context: hokusai
  filters:
    branches:
      only: master

only_release: &only_release
  context: hokusai
  filters:
    branches:
      only: release

workflows:
  default:
    jobs:
      - horizon/block:
          <<: *only_release
          context: horizon
          project_id: 11

      - artsy-remote-docker/build:
          <<: *not_staging_or_release
          name: docker_build
          context: hokusai
          post-steps:
            - run:
                name: Copy dupe report artifacts
                command: mkdir -p ./.artifacts && docker cp hokusai_force_1:/app/.artifacts ./
                when: always

      - duplicates:
          <<: *not_staging_or_release
          context: hokusai
          requires:
            - docker_build

      # Pre-staging
      - test:
          <<: *not_staging_or_release
          context: hokusai
          requires:
            - docker_build

      - acceptance:
          <<: *not_master_or_staging_or_release
      - acceptance_cypress:
          <<: *not_master_or_staging_or_release
      - build:
          <<: *not_staging_or_release

      - danger:
          <<: *not_staging_or_release

      # Staging
      - hokusai/push:
          name: push-staging-image
          <<: *only_master
          requires:
            - test
            - acceptance

      - hokusai/deploy-staging:
          <<: *only_master
          project-name: force
          requires:
            - push-staging-image

      # Release
      - validate_production_schema:
          <<: *only_release

      - hokusai/deploy-production:
          <<: *only_release
          requires:
            - horizon/block
            - validate_production_schema
